name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v2
      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: 
          pip install -U pytest
          pip install -r requirements.txt
      - name: Tests
        run: pytest
